baseURL = 'https://lambung-mangkurat-debate-society.netlify.app/'
languageCode = 'en-us'
title = 'Lambung Mangkurat Debate Society'
theme = "spectral"

[params]
fancyTitle = "Lambung Mangkurat<br> Debate Society" # title for frontpage, may include image
img = "/img/logo.png"
copyright = "Lambung Mangkurat<br> Debate Society"
description = '<i>Corgito Ergo Sum</i>'
startbuttonText = "About us"
startbuttonLink = "/posts/about"
body_is_markdown = true
images = ["/img/1.jpg"]
#custom_css = "foo.css"/img/1.jpg

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[[params.menu.main]]
url = '/division'
title = "Executives & Divisions"

[[params.menu.main]]
url = '/about'
title = "About us"

[[params.menu.main]]
url = '/contact'
title = "Contact us"

[[params.menu.main]]
url = '/admin'
title = "Admin"


[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'What is <br>Lambung Mangkurat Debate Society?'
body = '''
Lambung Mangkurat Debate Society is a part of the Lambung Mangkurat
University's organization that specialized in improving personal knowledge
through debating.
'''

[[params.one.icon]]
icon = "fa-users"
style = "1"
label = "Lorem"

[params.two]
enable = true

[[params.two.section]]
img = "img/4.webp"
title = 'What is <br />debating?'
body = 'A debate is an organized argument or contest of ideas in which the participants discuss a topic from two opposing sides. Those who agree with this statement or idea are the "Pro" side.  Those who will not agree with this statement or idea are the "Con" side.  Each side will show in an organized and clever way why they believe to have the right answers.  They will use examples and evidence to support their ideas while working towards a conclusion. '

[[params.two.section]]
img = "img/5.webp"
title = 'Why We focus on <br />personal growth through debating'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'Activites in <br> Lambung Mangkurat Debate Society'
body = '''
We have so many exciting activities in Lambung Mangkurat Debate Society to help improve personal growth in many ways:
'''

[[params.three.feature]]
icon = "fa-rocket"
title = "Intensive Training"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-trophy"
title = "Competition"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-users"
title = "Monthly Gathering"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = " fa-graduation-cap"
title = "Bootcamp"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."



[params.cta]
enable = true
title = "Have a question? <br> Check out our <u>FaQs</u> <br> before sending us a <u>message!</u>"
body = "Before you send us any questions, you could check out the Frequently Asked Questions!"

[[params.cta.link]]
href = "/faq"
text = "FAq"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "_"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = "lmds_ulm"
dribble = ""